--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Paroxity/PortalPM
build-by-default: true
branches:
- master
projects:
  PortalPM:
    path: ""
    libs:
      - src: Paroxity/Commando/Commando
        version: ^3.0.0
    lint:
      phpstan: false
...
