name: Portal
main: paroxity\portal\Portal
api: 4.0.0
author: ParoxityTeam
description: "Portal API implementation for PocketMine-MP"
version: 1.0.1
permissions:
  portal.command.transfer:
    default: op