name: PHPStan

on: [push, pull_request]

jobs:
  phpstan:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - name: Create Vendor Directory
        run: mkdir vendor
      - name: Download Virion Dependencies
        run: |
          wget -O vendor/Commando.phar https://poggit.pmmp.io/r/162923/Commando_dev-30.phar
      - name: Run PHPStan
        uses: paroxity/pmmp-phpstan-action@4.2.0
        with:
          phpstan-config: phpstan.neon.dist
